### PR TITLE
Support custom era names

### PR DESCRIPTION
**Pull request by upinetree**
Enable to customize the era names by a optional parameter, because I want to set other charactors for eras.

What do you think about this idea?

### CODE REVIEW

**Comment by tomiacannondale** [comment]
Thank you for PR!
I think this almost is ok.

But this PR does not work on ruby 1.9.3.(you use keyword arguments キーワード引数)
README says support ruby version is 1.9.3 and 2.0.0.
Sorry, this is not correct.(I test on ruby 1.9.3, 2.0.0, 2.1.2, 2.2.3)

Other person is using era_ja in ruby1.9.3?
If there are not any comments, I will merge this PR and fix README.

**Comment by upinetree** [comment]
Oh, sorry, I overlooked the versions in the README.
If there are needs i will fix it to be compatible with 1.9.3.

**Comment by tomiacannondale** [comment]
There were any response.
I merged this PR.

Thank you for contributions!
I will fix some documents(README, method comment), and update gem version.


I'm waiting for next your PR :penguin:

**Comment by upinetree** [comment]
Thank you for merging it and working for update! :smile:

**Pull request merged**
