### PR TITLE
add configration format %J only first year

### PR DESCRIPTION
**Pull request by kkawazoe**
Sometimes I want to limit the operation of `%J` to the first year only.

```ruby
# e.g.
Date.new(2019,5,1).to_era("%O%J-E年%-m月%-d日") #=> 令和元年5月1日
Date.new(2020,1,1).to_era("%O%J-E年%-m月%-d日") #=> 令和2年1月1日
```

Therefore, we have added a set value to limit the operation of `%J` to the first year only.
The default value is the same as before, so users who want the existing behavior will not be affected.

### CODE REVIEW

**Comment by tomiacannondale** [comment]
Thank you for your PR!

I will check your PR after the new year.

**Comment by tomiacannondale** [comment]
Sorry for late!

I want to more talk about this PR!

Let me know what you think.

## I want to more hear your use case

Adding `EraJa.configuration` is good idea. But if your project doese not always use this setting ( `format_era_only_first_year_kanji == true `), I think Adding `EraJa.configuration` is too much. 

I think more good idea that is adding new argument.

Please talk to me your use case.

## I think configuration name is not good

When `format_era_only_first_year_kanji` is true, era_ja outputs figure(ex 2).I think that this changes behavior of except the first year.So `format_era_only_first_year_kanji` (最初の1年だけを漢字にする) does not fit this behavior.I think more fit `2年目以降を数字にする` .

or

Change behavior when we do not use `%J` .

Ex:

```ruby
EraJa.configuration.format_era_only_first_year_kanji = true
Date.new(2019,5,1).to_era("%O%-E年%-m月%-d日") #=> 令和元年5月1日  # change!
Date.new(2020,1,1).to_era("%O%-E年%-m月%-d日") #=> 令和2年1月1日   # not chage

EraJa.configuration.format_era_only_first_year_kanji = false
Date.new(2019,5,1).to_era("%O%-E年%-m月%-d日") #=> 令和1年5月1日   # not chage
Date.new(2020,1,1).to_era("%O%-E年%-m月%-d日") #=> 令和2年1月1日   # not chage
```

**Comment by kkawazoe** [comment]
Thanks for the review PR.

> I want to more hear your use case

When using the Japanese calendar, especially in official documents,
it is Japanese customary to write the number of years in Kanji only for the first year and in numbers
for the second and subsequent years.

>I think more good idea that is adding new argument.

Certainly, once again, adding a new argument seems like a better idea!

**Comment by kkawazoe** [comment]
When adding a new option
Should I close this PR and create another one?

**Comment by tomiacannondale** [comment]
Yes! Please 😃

**Pull request closed without merging**
