### PR TITLE
Support 1 digit era year

### PR DESCRIPTION
**Pull request by risacan**
# Why? 🤔 
Sometimes you want to control digits for era year.

For example...

The application paper for year end adjustment in Japan, uses 1 digit era year for the title. 
( [like this](https://www.nta.go.jp/taxes/tetsuzuki/shinsei/annai/gensen/pdf/r2bun_02.pdf) )
It's not `令和02年`, it's `令和2年`

It is more user-friendly if you use the exact same name on your interface. 😃 

# What I did ✔️ 
* Add format `%-E` to control digits
* Add spec

### CODE REVIEW

**Comment by tomiacannondale** [comment]
Thank you for PR 😄 
I think `%-E` is good.
Because this is same as [strftime(3)](https://pubs.opengroup.org/onlinepubs/009695399/functions/strftime.html) .

First concept of era_ja is as close to [Time#strftime](https://rurema.clear-code.com/2.6.0/method/Time/i/strftime.html) .
[Time#strftime](https://rurema.clear-code.com/2.6.0/method/Time/i/strftime.html) was created with reference to [strftime(3)](https://pubs.opengroup.org/onlinepubs/009695399/functions/strftime.html) specification.

**Comment by tomiacannondale** [comment]
Sorry!
I changed status **Draft** to **Open** 
I have no idea to restore status to Draft...

**Comment by risacan** [comment]
@tomiacannondale Thank you for the comment and I'm sorry that it took time tor reply!
I will update comment and add samples  :+1:

**Comment by risacan** [comment]
@tomiacannondale 
I updated the PR comment. I also updated README. 😃

**Comment by tomiacannondale** [comment]
Thank you for PR!

I released new version(1.2.0)

I'm looking forward to the next PR 😄

**Comment by risacan** [comment]
Thank you so much!

**Pull request merged**
